# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxAlamofireEx' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxAlamofireEx
  pod 'ObjectMapper'
  pod 'RxAlamofire'
  pod 'RxCocoa'
  pod 'RxSwift'
  pod 'SwiftyJSON'
  pod 'Then'

  target 'RxAlamofireExTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxAlamofireExUITests' do
    # Pods for testing
  end

end
